### ISSUE TITLE
Does this work with Bluebird Promises?

### ISSUE THREAD

**Issue by mcqueenorama** [cruzrr/node-weedfs#11]
I get an error when I try to use Bluebird with this via promisifyAll.  Using the sample code, it works on its own, but when I tweek it to run with promises and use promisifyAll I get:

bash-3.2$ node dev.js 

/Users/bmcquee/dev/validate-and-replicate/node_modules/weed-fs/lib/weedfs.js:58
			opts.count = 1;
			           ^
TypeError: Cannot set property 'count' of undefined
    at Object.WeedFSClient.write (/Users/bmcquee/dev/validate-and-replicate/node_modules/weed-fs/lib/weedfs.js:58:15)
    at Object.<anonymous> (/Users/bmcquee/dev/validate-and-replicate/dev.js:11:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
bash-3.2$

**Comment by phal0r** [comment]
Finally I had time for the rewrite to support native Promises and Streams2 (without request module) -> https://github.com/atroo/node-weedfs
