### ISSUE TITLE
read with fileWriteStream has occured exception.

### ISSUE THREAD

**Issue by breaklee** [cruzrr/node-weedfs#14]
how can i handle this error?
=== code ===
var st = fs.createWriteStream("local-file-path");
weedfs.read(item.fid, fs);

=== error ===
stream.js:65
  dest.on('drain', ondrain);
       ^
TypeError: undefined is not a function
    at Request.Stream.pipe (stream.js:65:8)
    at Request.pipe (/Users/breaklee/Documents/project/eazler/moez-chat/node_modules/weed-fs/node_modules/request/request.js:1514:34)
    at /Users/breaklee/Documents/project/eazler/moez-chat/node_modules/weed-fs/lib/weedfs.js:150:23
    at Request._callback (/Users/breaklee/Documents/project/eazler/moez-chat/node_modules/weed-fs/lib/weedfs.js:116:4)

**Comment by ablakely** [comment]
Shouldn't fs be st in the .read() call?
